### ISSUE TITLE
Support MP4 as input streams

### ISSUE THREAD

**Issue by epiclabsDASH** [epiclabs-io/epic-video-comparator#2]
It would be nice if epic-video-comparator support MP4 video sources, apart from HLS and MPEG-DASH.

**Comment by adripanico** [comment]
Done in e55675a (upgrading to @epiclabs/epic-video-player v0.0.11).

**Comment by PhilippeR** [comment]
I don't find how use mp4 in demo page.  Is it up to date ?

**Comment by adripanico** [comment]
Just place a valid URL pointing to a mp4 asset:

```
var comparatorConfig = {
  leftUrl: 'http://techslides.com/demos/sample-videos/small.mp4',
  rightUrl: 'http://techslides.com/demos/sample-videos/small.mp4'
};
window.myComp = new evc.Comparator(comparatorConfig, document.getElementById('comparator-container'));
```

**Comment by PhilippeR** [comment]
Thank you (in fact,  I had in mind local files on my hard drive).

**Comment by adripanico** [comment]
In this case, the best option is to serve those files with a local web server.

The are several available tools for quickly doing this like [httpserver](https://www.npmjs.com/package/httpserver).

Do you think is it really interesting to add the local files option into the library? I can think on how to integrate it.

**Comment by PhilippeR** [comment]
Thank you. Indeed, I already have this kind of tool installed. That should be useful. In my case, I wanted to compare local encodings with each other. i let you see.
