### ISSUE TITLE
Improve management of fullscreen feature in mobile devices

### ISSUE THREAD

**Issue by epiclabsDASH** [epiclabs-io/epic-video-comparator#6]
When running in a mobile devices, switch to fullscreen mode should rotate the screen automatically.

**Comment by adripanico** [comment]
Fullscreen capabilities have been improved in version 0.0.4.

* Right stats position fixed on fullscreen.
* Fullscreen mode now works fine for any video aspect ratio.

Still working on autoset screen orientation when entering in fullscreen on mobile devices (https://developer.mozilla.org/en-US/docs/Web/API/Screen/lockOrientation).

**Comment by adripanico** [comment]
Released with version 0.0.5.
